### ISSUE TITLE
Add block explorer feature

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#124]
Add an option to deploy a (Big Dipper) block explorer.

**Comment by makeworld-the-better-one** [comment]
Working on #6, updating for latest releases and updated [docs](https://docs.bigdipper.live/) then testing and going through checkboxes.

**Comment by makeworld-the-better-one** [comment]
Ongoing issues/PRs (copied from #6)

- https://github.com/forbole/bdjuno/issues/449
- https://github.com/forbole/big-dipper-2.0-cosmos/pull/959

These aren't blockers. The issue they address is ports being open to the public when they shouldn't be, but I don't think it's a security issue.
