### ISSUE TITLE
Add a chain agnostic role based on gaia

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#129]
We need a new name for the main role used to set up a node.
Options:
- `cosmos`
- `node`
- `cosmos-node`

**Comment by YurkoWasHere** [comment]
I have been thinking on how to deal with this multi chain support part. I think that the best route would be to leave/abandon/depricate the existing Gaia role in favor of a new chain-agnostic role.

The chain agnostic role (which is to be named) will start of as a copy of the Gaia. 

This would allow the code to continue running until this new role matures into a point that makes sense. 

The goal would be to try to remove Gaia (or other chain) specific functions out of this role, into a separate role (or task TBD) and essential build the equivalent of a `base-class` for cosmos.

**Comment by dasanchez** [comment]
> I think that the best route would be to leave/abandon/depricate the existing Gaia role in favor of a new chain-agnostic role.
...
> The chain agnostic role (which is to be named) will start of as a copy of the Gaia.

This makes sense, I agree on both points.

**Comment by YurkoWasHere** [comment]
Todo
- [ ] Decide the name of this role (https://github.com/hyphacoop/cosmos-ansible/issues/129#issue-1309557907)
- [ ] Decide the name of all `gaia_*` parameters
- [ ] Decide on chain username (currently gaia)
- [ ] Decide on how chain parameters are defined
- [ ] Decide when fork will happen

**Comment by dasanchez** [comment]
I made a couple of tables to help us inform the above decisions:
https://docs.google.com/document/d/1-ce2yTHeMKP6Lc-2wYPrzidu9rmWxvUmfT2bfaYKZS0/edit#

**Comment by dasanchez** [comment]
Closed in `next`branch
