### ISSUE TITLE
Set parameters automatically when joining a network

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#130]
If I want to join the Theta testnet, we could query these from an RPC server:
- Chain ID (can be obtained via the `/status` endpoint)
- Gaia version (can be obtained via the `/abci_info` endpoint)

Or even better, use the chain registry:
https://chain-registry.netlify.app/
https://github.com/cosmos/chain-registry
https://registry.ping.pub/
https://registry.ping.pub/chain.schema.json

**Comment by dasanchez** [comment]
We can use the chain registry:
https://chain-registry.netlify.app/

**Comment by ASoTNetworks** [comment]
I have change it to use the chain registry for the mainnet and added a mainnet test workflow.

For testnet we have to open a PR to change the gaiad version to v7 before that will work.
