### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#146]
### Features

- One-line node deployment
- Chain installation and configuration
  - Gaia v6.0.4 to v7.0.2
- Relayer installation
  - Hermes
- Faucet REST server
- Monitoring and alerting
  - Node exporter setup
  - Prometheus configuration
  - PANIC configuration
- Node control operations
  - Start, stop, restart, reset
- Testing via GitHub Actions
  - Deploy a fresh state local testnet
  - Deploy a stateful local testnet
  - Join the Theta testnet

The following PRs will be closed beforehand:
- #138 
- #139 
- #141 
- #143 
- #144

**Comment by uditvira** [comment]
nice :)

**Comment by dasanchez** [comment]
Release v0.1.0 has been published:
https://github.com/hyphacoop/cosmos-ansible/releases/tag/v0.1.0
