### ISSUE TITLE
Review Playbook Variables doc

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#152]
The [Playbook Variables Overview](https://github.com/hyphacoop/cosmos-ansible/blob/main/docs/Playbook-Variables.md) is missing a few entries:
- `gaiad_bond_denom`
- `gaiad_binary_release`
- `gaiad_binary_source`

Review the variables from the gaia role defaults and update as appropriate.

**Comment by YurkoWasHere** [comment]
These new ones should be added as well

https://github.com/hyphacoop/cosmos-ansible/pull/138#issue-1311796071

May also be a good idea to link this from the README.md to be able to find it easier.
