### ISSUE TITLE
Speed up genesis file copy

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/cosmos-ansible#19]
We should try speeding up the genesis_file copying

We tried checking the file length and not loading if the length of the existing file is the same, but that broke easily.

Another approach we could try taking is by looking at the `mtime` of the genesis files, and if the file we have locally is more recent than the remote file, we should update it.

**Comment by ASoTNetworks** [comment]
Another option is also gzip the file and extract on the nodes after upload.

**Comment by ASoTNetworks** [comment]
Opened PR #39 to support gzipped genesis file `genesis.json.gz` to extract on the node after uploading.
