### ISSUE TITLE
Start a multi-node testnet with fresh state

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-ansible#20]

**Comment by uditvira** [comment]
1 node is initialized that creates the genesis. this genesis is then copied over to the rest of the network

**Comment by dasanchez** [comment]
For reference (via @YurkoWasHere) 
IPFS code for bootstrapping multiple provisioned nodes

Task for collecting the IPFS ID from a specific node within the same ansible.
It appends the result to array fact ipfs_bootstrap
- https://github.com/starlinglab/integrity-deploy/blob/main/roles/ipfs/tasks/collect_ipfs_id.yml

Ansible code that loops through my IPFS group
- https://github.com/starlinglab/integrity-deploy/blob/main/roles/ipfs/tasks/main.yml#L76-L79

finally add the bootstraps to IPFS from the array created above
- https://github.com/starlinglab/integrity-deploy/blob/main/roles/ipfs/tasks/main.yml#L82-L87
