### ISSUE TITLE
Make it easier to reset/start/stop specific nodes without running an entire playbook

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-ansible#23]
Ideas https://github.com/qdriven/cosmos-gaia-ansible

**Comment by ASoTNetworks** [comment]
Added tags to ansible playbook to allow running parts of it. 

Made a script to easily call the tags https://github.com/hyphacoop/cosmos-ansible/tree/theta-testnet#gaia-controlpy-script

**Comment by uditvira** [comment]
PR #7 should close this issue.
