### ISSUE TITLE
Add public wiki to Cosmos Ansible

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-ansible#30]

**Comment by uditvira** [comment]
A lot of this info is in here https://github.com/hyphacoop/cosmos-configurations-private/wiki#worklogs 
need to clean up and remove private info

**Comment by dasanchez** [comment]
Please review:
https://github.com/hyphacoop/cosmos-configurations-private/wiki/Multi-Node-Testnet-Setup
https://github.com/hyphacoop/cosmos-ansible/blob/three-node-example/examples/README.md

**Comment by uditvira** [comment]
I'd add a sentence here like this:

> We will use a scenario in which several hosts need to be set up on the `cosmostest.network` domain. This is an example domain, you should replace this with your own.

In here, https://github.com/hyphacoop/cosmos-ansible/blob/three-node-example/examples/README.md#start-a-three-node-testnet shouldn't we be using the public facing mnemonics?

Could we also make folders for these? Perhaps like this: 
* `validator-keys/<validator-name>/node_key.json`
* `validator-keys/<validator-name>/priv_validator_key.json`
* `validator-keys/<validator-name>/self-delegation-wallet-mnemonic.txt`

**Comment by dasanchez** [comment]
Make the guides for multi-node testnet setup and monitoring part of the repo in a `docs` folder.
