### ISSUE TITLE
Return mnemonic after generating keys

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#34]
Is there any use for getting back all mnemonics generated after running a playbook? 
I'm looking at the [create_validator](https://github.com/hyphacoop/cosmos-ansible/blob/44c63879bec2383e55b64faef58b00358bf52ca2/roles/gaia/tasks/main.yml#L139) task and wondering if it would be useful to list all accounts/keys/mnemonics as part of the play summary.

**Comment by dasanchez** [comment]
It's not good practice to print mnemonic to the screen.
Options:
- Save mnemonic to the home folder of the target host in a txt

**Comment by ASoTNetworks** [comment]
Opened PR #41 for this.
