### ISSUE TITLE
Persistent Peers Injection - Dream API

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/cosmos-ansible#5]
Assuming there are two groups: Peers that should be marked as persistent, peers that want those persistent peers injected into their `persistent_peers` list.

- Set up Gaia nodes (using Gaia role)
- Collect their IPs + public keys on persistent peers [based on this](https://stackoverflow.com/a/65944500)
    - Use `gaiad status` to get JSON for status info (e.g. `./go/bin/gaiad status --home /home/gaia/.gaiad/`)
    - Parse out just the node ID and listenaddr port
    - Register as a variable
    - Use the `inventory_hostname` for the address (can this be used instead of an IP?)
    - Register a variable `persistent_peer` from `{{id}}@{{hostname}}:{{p2p_port}}`
- Inject persistent peers
    - Iterate through hosts in persistent peers `{% for host in groups.persistent_peers %}`
    - Skip own hostname
    - Get the `persistent_peer` variable out `{{hostvars[host].persistent_peer}}`
    - Do this to get a line of persistent peers (comma separated?)
    - Generate an ansible_vars.json file similar to gaiad role, by specifying `{"config.toml": {"p2p.persistent_peers": {{persistent_peers | json}} }}`
    - Run [copy-config-vars.py](https://github.com/hyphacoop/cosmos-ansible/blob/main/roles/gaia/files/copy_config_vars.py) to inject the variable into the gaia config
    - Reboot the gaiad or cosmovisor service

**Comment by RangerMauve** [comment]
Ping @uditvira plz to review

**Comment by RangerMauve** [comment]
TODO: Check these end to end tests to see how they do persistent peer injection: https://github.com/cosmos/gaia/pull/1253/files

**Comment by uditvira** [comment]
- `gaiad tendermint show-node-id` is helpful
- fixing node key guarantees the node id is fixed

**Comment by dasanchez** [comment]
https://github.com/hyphacoop/cosmos-ansible/tree/main/examples#start-a-three-node-testnet-from-scratch
