### ISSUE TITLE
Make ~/.gaia the default home

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#75]
The default home for Gaia is `~/.gaia`:
https://github.com/cosmos/gaia/blob/2f79bc3be833eb346138506f67e8bf9469af58c3/app/app.go#L254

The `gaia` ansible role uses `~/.gaiad` as the default:
https://github.com/hyphacoop/cosmos-ansible/blob/a6fec71fa74ffd9e98215b0983c98a983cb432ca/roles/gaia/defaults/main.yml#L5

This means we have to use the `--home ~/.gaiad` flag every time we want to run `gaiad` commands.
If a user wants to avoid the extra typing after the node is set up, they would have to set the `gaiad_home` variable either in the inventory file or in the `ansible-playbook` command.

@uditvira @ASoTNetworks do you see any drawbacks to making this change?

**Comment by ASoTNetworks** [comment]
Doing some initial testing changing `gaiad_home` seems to work fine.
Can run gaiad commands without setting `--home`

**Comment by dasanchez** [comment]
Thanks @ASoTNetworks! 
I also noticed we should upgrade this line to use the `gaiad_home` variable:
https://github.com/hyphacoop/cosmos-ansible/blob/a6fec71fa74ffd9e98215b0983c98a983cb432ca/roles/node-exporter/tasks/main.yml#L56

**Comment by ASoTNetworks** [comment]
Updated that and tested prometheus monitoring
