### ISSUE TITLE
Test upgrading on a stateful genesis

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#83]
- Use the `cosmos-genesis-tinkerer` repo to produce a tinkered genesis file from a mainnet export periodically.
  - This tinkered file would include a pre-set faucet account and a validator one with majority voting power.
- Add another test to the CI workflow that runs a software upgrade on a stateful chain using the tinkered genesis file.

**Comment by dasanchez** [comment]
We can use a temporary node whose only purpose is to generate an exported genensis file.
The chain registry would be useful for getting sync peers information:
https://github.com/cosmos/chain-registry
https://chain-registry.netlify.app/
https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/chain.json

**Comment by ASoTNetworks** [comment]
Currently being blocked by low power Github Actions VM. Test does not compete in time during the 58 minutes limit.
It looks like there is work being done that will allow us to use more powerful runners in the future https://github.com/github/roadmap/issues/161

**Comment by ASoTNetworks** [comment]
For a workaround we can do the test in the same DO VM when doing the exporting to also try the upgrade process and push the status into the repo until Github supports more powerful runners.

**Comment by dasanchez** [comment]
> For a workaround we can do the test in the same DO VM when doing the exporting to also try the upgrade process and push the status into the repo until Github supports more powerful runners.

Sounds good! We might also have to do this if we want to implement a workflow for joining the theta testnet.

**Comment by dasanchez** [comment]
GitHub will disable LFS if we go over 150% of our quota, we need to find a sustainable storage solution for genesis files.

**Comment by dasanchez** [comment]
Closed with #110
